services:
  metagolf.demo:
    image: ${DOCKER_REGISTRY-}metagolf.demo
    container_name: metagolf.demo
    restart: unless-stopped
    volumes:
      - /var/lib/metagolf-demo/logs:/app/logs
    ports:
      - "3000:80"
      - "3001:443"
    environment:
      - NODE_ENV=production
