services:
  metagolf.demo:
    image: ${DOCKER_REGISTRY-}metagolf.demo.staging
    container_name: metagolf.demo.staging
    build:
      context: .
      dockerfile: Dockerfile.staging
    ports:
      - "3500:3500"
      - "3501:3501"
