server {
    listen 80;
    server_name demo.metagolf.ca;

    location / {
        proxy_pass http://localhost:3500; # or whatever internal service you want to forward traffic to
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
